In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("diabetes_prediction_dataset.csv")
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns",None)
data.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [3]:
data.shape

(100000, 9)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [5]:
data.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [6]:
data = data.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

In [7]:
data['gender'].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [8]:
data['gender'] = data['gender'].str.replace("Other","Female")

In [9]:
data['gender'].value_counts()

gender
Female    58570
Male      41430
Name: count, dtype: int64

In [10]:
data['heart_disease'].unique()

array([1, 0], dtype=int64)

In [11]:
chn = {
    1: "high blood Pressure",
    0: "Normal blood pressure"
}
data['hypertension']=data['hypertension'].replace(chn).astype("object")
data.sample(3)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99311,Male,19.0,Normal blood pressure,0,No Info,24.50,5.7,158,0
48042,Female,72.0,Normal blood pressure,0,No Info,21.06,6.6,85,0
41933,Male,80.0,Normal blood pressure,0,former,27.32,5.8,80,0

In [12]:
data['heart_disease'].unique()

array([1, 0], dtype=int64)

In [13]:
data['heart_disease']=data['heart_disease'].map({1:'Heart Disease',0:'No Heart Disease'}).astype("object")
data.sample(3)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
13260,Male,50.0,Normal blood pressure,No Heart Disease,current,27.32,5.0,145,0
12989,Female,70.0,Normal blood pressure,No Heart Disease,No Info,23.50,3.5,80,0
87201,Female,9.0,Normal blood pressure,No Heart Disease,never,15.68,3.5,130,0

In [14]:
data['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [15]:
data['smoking_history']=data['smoking_history'].map({'never':'Never','No Info':'No Information','current':'Currently','former':'Former','ever':'Ever','not current':"Not Currently"})
data.sample(3)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
90509,Female,33.0,Normal blood pressure,No Heart Disease,Not Currently,27.32,5.0,80,0
81563,Female,55.0,Normal blood pressure,No Heart Disease,Currently,31.05,4.5,159,0
73529,Female,39.0,Normal blood pressure,No Heart Disease,Never,33.94,4.8,100,0

In [16]:
data = data.rename(columns={'bmi':'BMI_Level'})
data.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'BMI_Level', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [17]:
data['HbA1c_level'].unique()

array([6.6, 5.7, 5. , 4.8, 6.5, 6.1, 6. , 5.8, 3.5, 6.2, 4. , 4.5, 9. ,
       7. , 8.8, 8.2, 7.5, 6.8])

In [18]:
data['blood_glucose_level'].unique()

array([140,  80, 158, 155,  85, 200, 145, 100, 130, 160, 126, 159,  90,
       260, 220, 300, 280, 240], dtype=int64)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  object
 3   heart_disease        100000 non-null  object
 4   smoking_history      100000 non-null  object
 5   BMI_Level            100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(2), object(4)
memory usage: 6.9+ MB

In [20]:
X=data.drop(columns=['diabetes'])
y=data['diabetes']
X=X.dropna()
y=y.dropna()
X.shape, y.shape

((100000, 8), (100000,))

In [21]:
print(X.isnull().sum())
print(y.isnull().sum())

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
BMI_Level              0
HbA1c_level            0
blood_glucose_level    0
dtype: int64
0

In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X['age'] = imputer.fit_transform(X[['age']])
X['BMI_Level'] = imputer.fit_transform(X[['BMI_Level']])
X['HbA1c_level'] = imputer.fit_transform(X[['HbA1c_level']])

In [23]:
X.sample(3), y.sample(3)

(       gender   age           hypertension     heart_disease smoking_history  \
 7184     Male  47.0    high blood Pressure  No Heart Disease          Former
 16035    Male  55.0  Normal blood pressure  No Heart Disease           Never
 70640  Female  45.0  Normal blood pressure  No Heart Disease  No Information

        BMI_Level  HbA1c_level  blood_glucose_level
 7184       32.19          4.5                  126
 16035      29.29          7.5                  159
 70640      27.32          4.5                  200  ,
 32604    0
 13813    0
 33538    0
 Name: diabetes, dtype: int64)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [26]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((70000, 8), (30000, 8), (70000,), (30000,))

In [27]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer

In [28]:
cat_col = ['gender','hypertension','heart_disease','smoking_history']
num_col = ['age','BMI_Level','HbA1c_level','blood_glucose_level']

In [29]:
make_col = make_column_transformer((OneHotEncoder(handle_unknown="ignore",categories='auto'),cat_col),
                                (StandardScaler(with_mean=False),num_col),
                                remainder="passthrough"
)
make_col

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'hypertension', 'heart_disease',
                                  'smoking_history']),
                                ('standardscaler',
                                 StandardScaler(with_mean=False),
                                 ['age', 'BMI_Level', 'HbA1c_level',
                                  'blood_glucose_level'])])

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
regression = LogisticRegression()

In [32]:
from sklearn.pipeline import make_pipeline

In [33]:
pipe = make_pipeline(make_col, regression)
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'hypertension',
                                                   'heart_disease',
                                                   'smoking_history']),
                                                 ('standardscaler',
                                                  StandardScaler(with_mean=False),
                                                  ['age', 'BMI_Level',
                                                   'HbA1c_level',
                                                   'blood_glucose_level'])])),
                ('logisticregression', LogisticRegression())])

In [34]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'hypertension',
                                                   'heart_disease',
                                                   'smoking_history']),
                                                 ('standardscaler',
                                                  StandardScaler(with_mean=False),
                                                  ['age', 'BMI_Level',
                                                   'HbA1c_level',
                                                   'blood_glucose_level'])])),
                ('logisticregression', LogisticRegression())])

In [35]:
y_pred = pipe.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy : ", accuracy)

Accuracy :  0.9602666666666667

In [38]:
data.sample(10)

,gender,age,hypertension,heart_disease,smoking_history,BMI_Level,HbA1c_level,blood_glucose_level,diabetes
64998,Female,25.0,Normal blood pressure,No Heart Disease,No Information,27.32,5.8,85,0
99468,Female,41.0,Normal blood pressure,No Heart Disease,Never,22.59,7.5,155,1
73360,Female,17.0,Normal blood pressure,No Heart Disease,Never,24.03,4.8,159,0
10570,Female,77.0,Normal blood pressure,No Heart Disease,No Information,27.32,6.1,158,0
94008,Female,31.0,Normal blood pressure,No Heart Disease,Never,22.30,3.5,155,0
5552,Male,45.0,Normal blood pressure,No Heart Disease,Never,31.12,6.1,80,0
83184,Female,63.0,Normal blood pressure,No Heart Disease,Ever,35.24,5.0,200,0
70620,Male,73.0,high blood Pressure,No Heart Disease,No Information,27.32,6.1,200,0
63077,Female,19.0,Normal blood pressure,No Heart Disease,No Information,20.40,6.5,160,0
49716,Male,44.0,high blood Pressure,No Heart Disease,Never,37.43,6.6,159,0

In [39]:
predict_data = pd.DataFrame([['Female',60,'Normal blood pressure','No Heart Disease','Currently',59,7,140]],
                columns=['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
                           'BMI_Level', 'HbA1c_level', 'blood_glucose_level'])
predict_data

,gender,age,hypertension,heart_disease,smoking_history,BMI_Level,HbA1c_level,blood_glucose_level
0,Female,60,Normal blood pressure,No Heart Disease,Currently,59,7,140

In [40]:
Ans = pipe.predict(predict_data)
print(Ans)
if Ans == 1:
    print("You are making new history because you have diabetes.💥💥")
else:
    print("Congratulation, you have not diabetes.🍾🍾")

[1]
You are making new history because you have diabetes.💥💥

In [41]:
import pickle

In [42]:
pickle.dump(pipe,open("pipe.pickle","wb"))
pickle.dump(data,open("data.pickel","wb"))
print("Succesfully Pickle File created")

Succesfully Pickle File created